# Generated by Django 5.0 on 2023-12-21 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Наименование рубрики', max_length=20, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активна ли рубрика?')),
                ('priority', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Приоритет')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('parent_rubric', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique_for_date='published', verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('kind', models.CharField(blank=True, choices=[(None, 'Выберите тип публикации'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Rent')], default='Выберите тип публикации', max_length=1)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
    ]
