# Generated by Django 4.2.8 on 2023-12-21 13:14

import bboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_options_bb_kind_alter_bb_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=models.SET(bboard.models.Bb.get_first_rubric), to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='parent_rubric',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric'),
        ),
    ]
