# Generated by Django 4.2.8 on 2023-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_rubric_alter_rubric_parent_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published')},
        ),
        migrations.AddIndex(
            model_name='bb',
            index=models.Index(condition=models.Q(('price__lte', 10000)), fields=['-published', 'title'], name='bb_main'),
        ),
        migrations.AddIndex(
            model_name='bb',
            index=models.Index(fields=['title', 'price', 'rubric'], name='bboard_bb_title_e42980_idx'),
        ),
    ]
