# Generated by Django 5.0 on 2023-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_rubric_is_active_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активна ли рубрика?'),
        ),
    ]
