# Generated by Django 4.2.8 on 2023-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_rubric_change_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='change_time',
        ),
        migrations.AddField(
            model_name='bb',
            name='change_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения'),
        ),
    ]
