# Generated by Django 5.0 on 2023-12-25 14:21

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_alter_bb_unique_together_bb_bb_main_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bb',
            name='bb_main',
        ),
        migrations.RemoveIndex(
            model_name='bb',
            name='bboard_bb_title_e42980_idx',
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[bboard.models.MailExistsValidation], verbose_name='Описание'),
        ),
    ]
