# Generated by Django 4.2.8 on 2023-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_options_alter_bb_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
