# Generated by Django 5.0 on 2023-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_rubric_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, unique_for_date='published', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, help_text='Наименование рубрики', max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
