# Generated by Django 4.2.8 on 2023-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_remove_rubric_change_time_bb_change_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='change_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения'),
        ),
    ]
