# Generated by Django 5.0 on 2023-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_rubric_options_rubric_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
