# Generated by Django 5.0 on 2023-12-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_alter_rubric_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='priority',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Приоритет'),
        ),
    ]
