# Generated by Django 5.0 on 2023-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_rubric_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='Создано'),
        ),
    ]
