# Generated by Django 5.0 on 2023-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_alter_rubric_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='created_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Создано'),
        ),
    ]
