# Generated by Django 5.0 on 2023-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0021_alter_bb_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='approved_by_moderator',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
    ]
