# Generated by Django 5.0 on 2023-12-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0022_bb_approved_by_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='approved_by_moderator',
        ),
    ]
