# Generated by Django 5.0 on 2023-12-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0023_remove_bb_approved_by_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='parent_rubric',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.rubric'),
        ),
    ]
