# Generated by Django 5.0 on 2023-12-21 13:13

import bboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0024_rubric_parent_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=models.SET(bboard.models.Bb.get_first_rubric), to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='parent_rubric',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric'),
        ),
    ]
