# Generated by Django 5.0 on 2023-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0026_alter_bb_options_alter_bb_unique_together_bb_bb_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
