# Generated by Django 5.0 on 2023-12-25 14:21

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0029_alter_bb_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[bboard.models.MailExistsValidation], verbose_name='Описание'),
        ),
    ]
