# Generated by Django 5.0 on 2023-12-25 14:43

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0031_alter_bb_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, help_text='Наименование рубрики', max_length=20, unique=True, validators=[bboard.models.Rubric.title_validation], verbose_name='Название'),
        ),
    ]
