# Generated by Django 5.0 on 2023-12-25 14:49

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0032_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.models.Bb.price_validation], verbose_name='Цена'),
        ),
    ]
